export const teamData = props => (
	{
		playerIds: props.playerIds.map(e => e.id),
		score: props.score,
		isOrange: props.isOrange,
		possessionTime: props.stats.posession.possessionTime,
		turnovers: props.stats.posession.turnovers,
		turnoversOnMyHalf: props.stats.posession.turnoversOnMyHalf,
		turnoversOnTheirHalf: props.stats.posession.turnoversOnTheirHalf,
		wonTurnovers: props.stats.posession.wonTurnovers,
		totalHits: props.stats.hitCounts.totalHits,
		totalPasses: props.stats.hitCounts.totalPasses,
		totalSaves: props.stats.hitCounts.totalSaves,
		totalShots: props.stats.hitCounts.totalShots,
		totalDribbles: props.stats.hitCounts.totalDribbles,
		totalDribbleConts: props.stats.hitCounts.totalDribbleConts,
		totalAerials: props.stats.hitCounts.totalAerials,
		totalClears: props.stats.hitCounts.totalClears,
		timeOnGround: props.stats.centerOfMass.positionalTendencies.timeOnGround,
		timeLowInAir: props.stats.centerOfMass.positionalTendencies.timeLowInAir,
		timeHighInAir: props.stats.centerOfMass.positionalTendencies.timeHighInAir,
		timeInDefendingHalf: props.stats.centerOfMass.positionalTendencies.timeInDefendingHalf,
		timeInAttackingHalf: props.stats.centerOfMass.positionalTendencies.timeInAttackingHalf,
		timeInDefendingThird: props.stats.centerOfMass.positionalTendencies.timeInDefendingThird,
		timeInNeutralThird: props.stats.centerOfMass.positionalTendencies.timeInNeutralThird,
		timeInAttackingThird: props.stats.centerOfMass.positionalTendencies.timeInAttackingThird,
		timeBehindBall: props.stats.centerOfMass.positionalTendencies.timeBehindBall,
		timeInFrontBall: props.stats.centerOfMass.positionalTendencies.timeInFrontBall,
		timeNearWall: props.stats.centerOfMass.positionalTendencies.timeNearWall,
		timeInCorner: props.stats.centerOfMass.positionalTendencies.timeInCorner,
		timeOnWall: props.stats.centerOfMass.positionalTendencies.timeOnWall,
		averageDistanceFromCenter: props.stats.averageDistanceFromCenter,
		averageMaxDistanceFromCenter: props.stats.averageMaxDistanceFromCenter,
		timeClumped: props.stats.timeClumped,
		timeBoondocks: props.stats.timeBoondocks,
	}
)
